/** Selectores del elemento a resaltar en cada paso (mismo orden que `panelSteps.js`). */
const R = '[data-tour="dashboard-sidebar"]';

export const ADMIN_PANEL_TARGETS = [
  '[data-tour="manual-btn"]',
  `${R} [data-tour="sidebar"]`,
  `${R} [data-tour="sidebar-brand"]`,
  `${R} [data-tour="nav-section-principal"]`,
  `${R} [data-tour="nav-citas"]`,
  '[data-tour="section-citas"]',
  `${R} [data-tour="nav-buscar_citas"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-revision_citas"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-section-informes"]`,
  `${R} [data-tour="nav-analitica"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-section-operacion"]`,
  `${R} [data-tour="nav-horarios"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-section-administracion"]`,
  `${R} [data-tour="nav-equipo"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-auditoria"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-configuraciones"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="sidebar-user-profile"]`,
  `${R} [data-tour="sidebar-logout"]`,
];

export const LOGISTICA_PANEL_TARGETS = [
  '[data-tour="manual-btn"]',
  `${R} [data-tour="sidebar"]`,
  `${R} [data-tour="sidebar-brand"]`,
  `${R} [data-tour="nav-section-principal"]`,
  `${R} [data-tour="nav-citas"]`,
  '[data-tour="section-citas"]',
  `${R} [data-tour="nav-buscar_citas"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-revision_citas"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-historial"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-configuraciones"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="sidebar-user-profile"]`,
  `${R} [data-tour="sidebar-logout"]`,
];

export const PROVEEDOR_PANEL_TARGETS = [
  '[data-tour="manual-btn"]',
  `${R} [data-tour="sidebar"]`,
  `${R} [data-tour="sidebar-brand"]`,
  `${R} [data-tour="nav-section-principal"]`,
  `${R} [data-tour="nav-inicio"]`,
  '[data-tour="section-proveedor-inicio"]',
  `${R} [data-tour="nav-mis_citas"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-historial"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="nav-configuraciones"]`,
  '[data-tour="main-workspace"]',
  `${R} [data-tour="sidebar-user-profile"]`,
  `${R} [data-tour="sidebar-logout"]`,
];
